In [2]:
import numpy as np 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
exampl = np.array([['Male', 25], ['Female', 30], ['Trans', 21], ['Male',34],['Female',19]])
labenc = LabelEncoder()
exampl[:, 0] = labenc.fit_transform(exampl[:, 0])

In [3]:
exampl

array([['1', '25'],
       ['0', '30'],
       ['2', '21'],
       ['1', '34'],
       ['0', '19']], dtype='<U6')

In [4]:
labenc.classes_

array(['Female', 'Male', 'Trans'], dtype='<U6')

In [5]:
enc = OneHotEncoder(categorical_features = [0])
exampl = enc.fit_transform(exampl).toarray()
exampl

array([[ 0.,  1.,  0., 25.],
       [ 1.,  0.,  0., 30.],
       [ 0.,  0.,  1., 21.],
       [ 0.,  1.,  0., 34.],
       [ 1.,  0.,  0., 19.]])

In [15]:
enc.categorical_features, enc.feature_indices_, enc.n_values_, enc.sparse, enc.dtype, enc.feature_indices_

([0],
 array([0, 3], dtype=int32),
 array([3]),
 True,
 numpy.float64,
 array([0, 3], dtype=int32))

In [16]:
sc = StandardScaler()
# x(i) = (xi - mean(x)) / stddev(x)
# stddev(x) = sqrt(sigma dev-sq / n)
exampl = sc.fit_transform(exampl)

In [17]:
exampl

array([[-0.81649658,  1.22474487, -0.5       , -0.14377703],
       [ 1.22474487, -0.81649658, -0.5       ,  0.75482941],
       [-0.81649658, -0.81649658,  2.        , -0.86266219],
       [-0.81649658,  1.22474487, -0.5       ,  1.47371457],
       [ 1.22474487, -0.81649658, -0.5       , -1.22210476]])