In [1]:
import pandas as pd
import numpy as np
tdata=pd.DataFrame(data={'x1':[1,2,3,4], 'x2':[5,6,7,8], 'x3':[9,10,11,12], 'y':[0,1,0,1]})
tdata.columns=['x1','x2','x3','y']

User_Data = np.array(tdata)
features = User_Data[:,0:3]
labels = User_Data[:,3:4]

In [2]:
tdata

x1  x2  x3  y
0   1   5   9  0
1   2   6  10  1
2   3   7  11  0
3   4   8  12  1

In [3]:
User_Data

array([[ 1,  5,  9,  0],
       [ 2,  6, 10,  1],
       [ 3,  7, 11,  0],
       [ 4,  8, 12,  1]], dtype=int64)

In [4]:
features

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]], dtype=int64)

In [5]:
labels

array([[0],
       [1],
       [0],
       [1]], dtype=int64)

In [6]:
classes=np.unique(labels)
idx=labels==classes[0]
Yt=labels[idx]

In [7]:
Xt=features[idx,:]

IndexError: too many indices for array

In [9]:
classes

array([0, 1], dtype=int64)

In [10]:
idx

array([[ True],
       [False],
       [ True],
       [False]])

In [11]:
Yt

array([0, 0], dtype=int64)

In [12]:
print(np.shape(tdata))
print(np.shape(features))
print(np.shape(labels))
print(np.shape(idx))

(4, 4)
(4, 3)
(4, 1)
(4, 1)


In [13]:
# Which rows
idx[:,0] 

array([ True, False,  True, False])

In [14]:
Xt=features[idx[:,0],:]
Xt

array([[ 1,  5,  9],
       [ 3,  7, 11]], dtype=int64)